spring:
  application:
    name: blog-user
mybatis-plus:
  mapper-locations: /com/youlixiang/blog/user/mapper/xml/*.xml
  type-aliases-package: com.youlixiang.blog.user.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl