spring:
  application:
    name: blog-gateway
  cloud:
    gateway:
      routes:
        #用户路由
        - id: user_route
          uri: lb://blog-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        #文章路由
        - id: article_route
          uri: lb://blog-article
          predicates:
            - Path=/article/**
          filters:
            - StripPrefix=1
        #oss路由
        - id: oss_route
          uri: lb://blog-oss
          predicates:
            - Path=/oss/**
          filters:
            - StripPrefix=1